<?php

//Language variables used for AdminCP/Settings Page

$lang['default_title'] = "Site Settings";
$lang['default'] = "Here you can manage the settings for your site.  
					Click on a setting below to view or change its current configuration.<br><br>
					<b><u>Site Settings:</u></b><br>
					<a href='globals'>View or Edit Basic Site Settings</a><br>
					<a href='themes'>View or Edit Theme and Template Settings</a><br>								
					<a href='pound'>View or Edit Pound System Settings</a><br><br>";
$lang['plugins_title'] = "Plugin Settings";
$lang['plugins'] = "Listed here are all of the plugins that are using hooks to interface with the Mysidia Adoptables Admin CP.
					Clicking on a link below will redirect you to a page generated by the respecive plugin where you can change plugin-specific settings.<br /><br />";
$lang['no_plugins'] = "<b>There are currently no plugin hooks present.</b>";
$lang['basic_title'] = "Global Site Settings";
$lang['basic'] = "This page allows you to edit the basic settings for your Mysidia Adoptables installation.  
					Fill out the form below to change the settings.  
					Settings which need further explanation will have more information next to their area on the form.<br>";
$lang['basic_update_title'] = "Settings Updated Successfully";
$lang['basic_update'] = "The new site settings have been updated successfully. <a href='globals'>Click Here</a> to return to the settings manager.";					
$lang['themes_title'] = "Theme Manager";
$lang['themes'] = "This page allows you to change the theme for your website. Themes allow you to style your website.  
				  You can select a theme to use from the dropdown list below or you can install a new theme to your site using the theme installation form below.
				  To get more themes please visit the <a href='http://www.mysidiaadoptables.com/forum' target='_blank'>Mysidia Adoptables Support Forums</a>.<br>
				  <br><b><u>Select a Theme:</u></b><br>";
$lang['themes_install'] = "<b><u>Install a Theme:</u></b><br><br>";	
$lang['themes_update_name'] = "Type a name to use for this theme. This should be something to help you remember what this theme looks like.";
$lang['themes_update_folder'] = "This is the path to the folder that contains the theme's .tpl and .css file on your server. Usually the theme author will give you this value to paste into this box.";
$lang['themes_update_title'] = "Theme Updated Successfully";
$lang['themes_update_success'] = "The theme has been changed successfully!  <a href='theme'>Click Here</a> to change the site settings.</a>";
$lang['themes_update_failed'] = "It appears that the theme you selected is invalid or does not exist.  Please go back and try selecting another theme.";
$lang['themes_install_title'] = "Theme installed Successfully";
$lang['themes_install_success'] =  "The theme has been installed successfully to your site. 
									You may now <a href='theme'>set the theme as the default theme</a> if you so desire.";
$lang['themes_install_failed'] = "The theme you are trying to install cannot be found on this server at the specified URL. Please go back and double check that the path to the theme's HTML file is correct.
								  If you uploaded the theme and you are sure the URL is correct please make sure your web host does not have PHP's safe_mode configuration enabled as this can interfere with using or locating themes.";
$lang['pound_title'] = "Pound System Settings";
$lang['pound'] = "This page allows you to edit all settings for pound system, fill out the form below to change the settings.<br />
                  The form has two types of fields: Radio Button and Text. <br /> Radio buttons enable/disable a certain setting, some are dealing with advanced stuff.<br />		 		
				  For textbox, they must contain numerical values. Leave a field blank or enter the value 0 to disable a particular setting<br><br>";
$lang['pound_adopt'] = "Note if you enable pound system but disable re-adoption, users can pound but not re-adopt.";		  
$lang['pound_edited_title'] = "Pound Settings Updated Successfully";
$lang['pound_edited'] = "The Pound System Settings have been updated successfully. <a href='pound'>Click Here</a> to return to the pound settings manager.";

?>