<?php

//Language variables used for AdminCP/Image Page

$lang['manage_title'] = "Image Manager";
$lang['manage'] = "This page allows you to manage and delete all of the images that you have uploaded to your server.
				   You can select the image you wish to delete by selecting it with the button next to it.  
				   Once you delete an image, it's gone, but you can always reupload it.
				   Please note that if you delete an image that is in use by any of your members or adoptables 
				   this may break their adoptables.<br />";
$lang['upload_title'] = "Upload a new image";
$lang['upload'] = "This page allows you to upload a new adoptable image to the server.  
				   You may upload .gif, .png, or .jpg images no greater than 150 KB using the form below.
				   Uploaded images will be selectable from the drop down list of images when working with adoptables.<br />";
$lang['explain'] = "Enter a name for this image that will appear in the image drop down box for this image. This is here so you can remember what this image is. 
				    A good name would be something like <strong>Dog Adoptable Level 3</strong> so you remember what the image is.";
$lang['uploaded_title'] = "Upload Success";
$lang['uploaded'] = "The image file has been uploaded successfully!  It will now appear in the drop down list of available adoptables images.";
$lang['next'] = "<br><br><b><u>What would you like to do now?</u></b><br><br><a href='upload'>Upload Another Image</a>
			     <br><a href='../index'>Admin CP Home</a>";
$lang['delete_title'] = "File Deleted Successfully";
$lang['delete'] = "The file was deleted successfully. <a href='delete'>Click Here</a> to manage another file.";
$lang['nonexist'] = "Cannot delete file, it does not exist on the server.";
$lang['notwritable'] = "Cannot delete file, it is not writable.";
$lang['noid'] = "Cannot delete file, ID is invalid.";
$lang['extension'] = "The file type or extention you are trying to upload is not allowed!  
	                  You can only upload gif or png files to the server!";
$lang['file_notexist'] = "No File Exists!";
$lang['file_exist'] = "Your file already exists on the server! Please choose another file to upload or rename the file on your computer and try uploading it again!";
$lang['file_size'] = "The file you are trying to upload is too large!  Files must be under 150 KB.";
$lang['file_type'] = "The file you are trying to upload does not contain expected data. Are you sure that the file is a .gif, .jpg or a .png file?";
$lang['error'] = "There was an error uploading the file, please try again!";
$lang['settings_title'] = "Signature Settings";
$lang['settings'] = "This page allows you to change settings related to how the script handles adoptable signature images generated by the BBCode generator.";
$lang['gd_explain'] = "If you enable GD Signature Images for GIF files then all adoptables that use GIF files for their images 
					   will have their signature images modified by the GD image library before being output by the system. 
					   Enabling this setting will put the adoptable's name and owner on the image for the adoptable that is served by this server. 
					   Please note that if GD is not installed or enabled on this server this setting will not take effect and all images will fall back to the default method of showing signature images.";
$lang['altbb_explain'] = "If you enable this setting then an additional set of BBCode will be shown for all adoptables that will convert URLs such as click/siggy/20 to URLs such as /get/20.gif. 
                          You should only enable this if you have uploaded and edited the modified .htaccess file so that users can access the pets at their friendly URLs. 
						  If you have not uploaded the .htaccess file required for this then users who use the alternate BBCodes will not have their signature images work properly.<br>";
$lang['settings_updated_title'] = "Settings Updated Successfully";
$lang['settings_updated'] = "Your settings have been updated successfully. Please <a href='settings'>Click Here</a> to return to the settings manager.";
